// frontend-03/client/src/pages/MySubmissions.tsx
import { useEffect, useState } from 'react';
import { useLocation } from 'wouter';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { submissionAPI } from '@/lib/api';
import { toast } from 'sonner';
import { ArrowLeft, CheckCircle, Clock, AlertCircle } from 'lucide-react';

export default function MySubmissions() {
  const [, setLocation] = useLocation();
  const [submissions, setSubmissions] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    fetchMySubmissions();
  }, []);

  const fetchMySubmissions = async () => {
    setLoading(true);
    try {
      const response: any = await submissionAPI.getMySubmissions();
      if (response?.code === 0) {
        setSubmissions(response.data.list || []);
      } else {
        toast.error('获取提交列表失败');
      }
    } catch (error) {
      toast.error('获取提交列表失败');
    } finally {
      setLoading(false);
    }
  };

  const getStatusIcon = (submission: any) => {
    if (submission.score !== null && submission.score !== undefined) {
      return <CheckCircle className="w-5 h-5 text-emerald-600" />;
    }
    return <Clock className="w-5 h-5 text-yellow-600" />;
  };

  const getStatusText = (submission: any) => {
    if (submission.score !== null && submission.score !== undefined) {
      return '已批改';
    }
    return '待批改';
  };

  return (
    <div className="min-h-screen bg-gray-50">
      {/* 顶部导航 */}
      <nav className="bg-white border-b border-gray-200 shadow-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <Button
            variant="ghost"
            className="gap-2 text-emerald-600 hover:text-emerald-700"
            onClick={() => setLocation('/')}
          >
            <ArrowLeft className="w-4 h-4" />
            返回
          </Button>
        </div>
      </nav>

      {/* 主内容 */}
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900">我的提交</h1>
          <p className="text-gray-500 mt-1">查看你提交的所有作业</p>
        </div>

        {loading ? (
          <div className="text-center py-12">
            <div className="inline-block">
              <div className="w-8 h-8 border-4 border-emerald-200 border-t-emerald-600 rounded-full animate-spin"></div>
            </div>
            <p className="text-gray-500 mt-4">加载中...</p>
          </div>
        ) : submissions.length === 0 ? (
          <Card className="text-center py-12">
            <AlertCircle className="w-12 h-12 text-gray-300 mx-auto mb-4" />
            <p className="text-gray-500">暂无提交</p>
          </Card>
        ) : (
          <div className="space-y-4">
            {submissions.map((submission) => (
              <Card
                key={submission.id}
                className="hover:shadow-md transition-shadow p-6"
              >
                <div className="flex items-start justify-between">
                  <div className="flex-1">
                    <div className="flex items-center gap-3 mb-2">
                      {getStatusIcon(submission)}
                      <h3 className="text-lg font-semibold text-gray-900">
                        {submission.homework?.title}
                      </h3>
                    </div>

                    <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-4">
                      <div>
                        <p className="text-xs text-gray-500 mb-1">部门</p>
                        <p className="font-medium text-gray-900">
                          {submission.homework?.department_label}
                        </p>
                      </div>
                      <div>
                        <p className="text-xs text-gray-500 mb-1">提交时间</p>
                        <p className="font-medium text-gray-900">
                          {new Date(submission.submitted_at).toLocaleDateString('zh-CN')}
                        </p>
                      </div>
                      <div>
                        <p className="text-xs text-gray-500 mb-1">状态</p>
                        <p className="font-medium text-gray-900">
                          {getStatusText(submission)}
                        </p>
                      </div>
                      <div>
                        <p className="text-xs text-gray-500 mb-1">成绩</p>
                        {submission.score !== null && submission.score !== undefined ? (
                          <p className="font-bold text-emerald-600 text-lg">
                            {submission.score}分
                          </p>
                        ) : (
                          <p className="text-gray-500">-</p>
                        )}
                      </div>
                    </div>

                    {submission.comment && (
                      <div className="mt-4 p-3 bg-gray-50 rounded-lg border border-gray-200">
                        <p className="text-xs text-gray-500 mb-1">评语</p>
                        <p className="text-sm text-gray-700">{submission.comment}</p>
                      </div>
                    )}

                    {submission.is_excellent && (
                      <div className="mt-3 inline-block px-3 py-1 bg-yellow-100 text-yellow-700 text-xs font-semibold rounded-full">
                        ⭐ 优秀作业
                      </div>
                    )}
                  </div>
                </div>
              </Card>
            ))}
          </div>
        )}
      </main>
    </div>
  );
}

// Frontend/src/pages/MySubmissions.vue
<template>
  <div class="my-submissions">
    <!-- 顶部导航 -->
    <el-header class="app-header">
      <div class="header-left">
        <el-button type="primary" link @click="$router.back()">
          <el-icon><ArrowLeft /></el-icon>
          返回
        </el-button>
      </div>
      <div class="header-right">
        <el-dropdown>
          <span class="el-dropdown-link">
            {{ userStore.user?.nickname }}
            <el-icon class="el-icon--right"><ArrowDown /></el-icon>
          </span>
          <template #dropdown>
            <el-dropdown-menu>
              <el-dropdown-item @click="$router.push('/profile')">
                个人资料
              </el-dropdown-item>
              <el-dropdown-item @click="handleLogout">
                退出登录
              </el-dropdown-item>
            </el-dropdown-menu>
          </template>
        </el-dropdown>
      </div>
    </el-header>

    <el-main class="main-content">
      <div class="container">
        <div class="page-header">
          <h2>我的提交</h2>
          <p>查看你提交的所有作业</p>
        </div>

        <!-- 加载状态 -->
        <div v-if="loading" class="loading">
          <el-skeleton :rows="5" animated />
        </div>

        <!-- 提交列表 -->
        <div v-else class="submissions-list">
          <el-empty v-if="submissions.length === 0" description="暂无提交" />

          <el-timeline v-else>
            <el-timeline-item
              v-for="submission in submissions"
              :key="submission.id"
              :timestamp="formatDate(submission.submitted_at)"
              placement="top"
            >
              <el-card class="submission-card">
                <div class="card-header">
                  <h3 class="title">{{ submission.homework?.title }}</h3>
                  <div class="tags">
                    <el-tag type="info">{{ submission.homework?.department_label }}</el-tag>
                    <el-tag
                      v-if="submission.score !== null"
                      type="success"
                    >
                      {{ submission.score }}分
                    </el-tag>
                    <el-tag v-else type="warning">待批改</el-tag>
                    <el-tag v-if="submission.is_excellent" type="warning">
                      <el-icon><Star /></el-icon>
                      优秀
                    </el-tag>
                  </div>
                </div>

                <div class="card-content">
                  <div class="info-row">
                    <span class="label">提交时间：</span>
                    <span class="value">{{ formatDateTime(submission.submitted_at) }}</span>
                  </div>

                  <div v-if="submission.comment" class="comment">
                    <p class="comment-title">教师评语</p>
                    <p class="comment-text">{{ submission.comment }}</p>
                  </div>
                </div>
              </el-card>
            </el-timeline-item>
          </el-timeline>
        </div>
      </div>
    </el-main>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { ArrowLeft, ArrowDown, Star } from '@element-plus/icons-vue'
import { useUserStore } from '@/stores/user'
import { submissionAPI } from '@/utils/api'

const router = useRouter()
const userStore = useUserStore()

const submissions = ref<any[]>([])
const loading = ref(false)

const formatDate = (date: string) => {
  return new Date(date).toLocaleDateString('zh-CN')
}

const formatDateTime = (date: string) => {
  return new Date(date).toLocaleDateString('zh-CN', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
  })
}

const fetchMySubmissions = async () => {
  loading.value = true
  try {
    const data = await submissionAPI.getMySubmissions()
    submissions.value = data.list || []
  } catch (error) {
    ElMessage.error('获取提交列表失败')
  } finally {
    loading.value = false
  }
}

const handleLogout = () => {
  userStore.logout()
  router.push('/login')
}

onMounted(() => {
  fetchMySubmissions()
})
</script>

<style scoped lang="scss">
.my-submissions {
  width: 100%;
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}

.app-header {
  background-color: #10b981;
  color: white;
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0 20px;
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.1);

  .header-left {
    :deep(.el-button) {
      color: white;

      &:hover {
        background-color: rgba(255, 255, 255, 0.2);
      }
    }
  }

  .header-right {
    .el-dropdown-link {
      cursor: pointer;
      color: white;
      display: flex;
      align-items: center;
      gap: 8px;

      &:hover {
        opacity: 0.8;
      }
    }
  }
}

.main-content {
  flex: 1;
  padding: 20px;
  background-color: #f5f7fa;
}

.container {
  max-width: 900px;
  margin: 0 auto;
}

.page-header {
  margin-bottom: 30px;

  h2 {
    margin: 0 0 10px 0;
    font-size: 24px;
    color: #1f2937;
  }

  p {
    margin: 0;
    color: #6b7280;
  }
}

.loading {
  padding: 20px;
}

.submissions-list {
  :deep(.el-timeline) {
    .el-timeline-item {
      padding-bottom: 30px;
    }

    .el-timeline-item__content {
      padding-left: 20px;
    }
  }

  .submission-card {
    .card-header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      gap: 15px;
      margin-bottom: 15px;

      .title {
        margin: 0;
        font-size: 16px;
        font-weight: 600;
        color: #1f2937;
        flex: 1;
      }

      .tags {
        display: flex;
        gap: 8px;
        flex-wrap: wrap;
      }
    }

    .card-content {
      .info-row {
        display: flex;
        margin-bottom: 12px;
        font-size: 14px;

        .label {
          color: #9ca3af;
          width: 100px;
        }

        .value {
          color: #1f2937;
          font-weight: 500;
        }
      }

      .comment {
        margin-top: 15px;
        padding-top: 15px;
        border-top: 1px solid #e5e7eb;

        .comment-title {
          margin: 0 0 8px 0;
          font-size: 12px;
          color: #9ca3af;
          font-weight: 600;
        }

        .comment-text {
          margin: 0;
          color: #6b7280;
          font-size: 14px;
          line-height: 1.5;
        }
      }
    }
  }
}

@media (max-width: 768px) {
  .main-content {
    padding: 15px;
  }

  .submissions-list {
    .submission-card {
      .card-header {
        flex-direction: column;

        .tags {
          width: 100%;
        }
      }
    }
  }
}
</style>
