// frontend-03/src/pages/ExcellentSubmissions.vue
<template>
  <div class="excellent-submissions">
    <!-- 顶部导航 -->
    <el-header class="app-header">
      <div class="header-left">
        <el-button type="primary" link @click="$router.back()">
          <el-icon>
            <ArrowLeft />
          </el-icon>
          返回
        </el-button>
      </div>
      <div class="header-right">
        <el-dropdown>
          <span class="el-dropdown-link">
            {{ userStore.user?.nickname }}
            <el-icon class="el-icon--right">
              <ArrowDown />
            </el-icon>
          </span>
          <template #dropdown>
            <el-dropdown-menu>
              <el-dropdown-item @click="$router.push('/profile')">
                个人资料
              </el-dropdown-item>
              <el-dropdown-item @click="handleLogout">
                退出登录
              </el-dropdown-item>
            </el-dropdown-menu>
          </template>
        </el-dropdown>
      </div>
    </el-header>

    <el-main class="main-content">
      <div class="container">
        <div class="page-header">
          <h2>优秀作业展示</h2>
          <p>展示所有被标记为优秀的作业提交</p>
        </div>

        <!-- 加载状态 -->
        <div v-if="loading" class="loading">
          <el-skeleton :rows="5" animated />
        </div>

        <!-- 优秀作业列表 -->
        <div v-else class="submissions-list">
          <el-empty v-if="submissions.length === 0" description="暂无优秀作业" />

          <el-row :gutter="20">
            <el-col v-for="submission in submissions" :key="submission.id" :xs="24" :sm="12" :md="8">
              <el-card class="submission-card">
                <template #header>
                  <div class="card-header">
                    <span class="title">{{ submission.homework?.title }}</span>
                    <el-tag type="warning">
                      <el-icon>
                        <Star />
                      </el-icon>
                      优秀
                    </el-tag>
                  </div>
                </template>

                <div class="card-content">
                  <div class="student-info">
                    <span class="label">学生：</span>
                    <span class="value">{{ submission.student?.nickname }}</span>
                  </div>

                  <div class="info-row">
                    <span class="label">部门：</span>
                    <span class="value">{{ submission.homework?.department_label }}</span>
                  </div>

                  <div class="info-row">
                    <span class="label">成绩：</span>
                    <span class="score">{{ submission.score }}分</span>
                  </div>

                  <div class="info-row">
                    <span class="label">提交时间：</span>
                    <span class="value">{{ formatDate(submission.submitted_at) }}</span>
                  </div>

                  <div v-if="submission.comment" class="comment">
                    <p class="comment-title">教师评语</p>
                    <p class="comment-text">{{ submission.comment }}</p>
                  </div>
                </div>
              </el-card>
            </el-col>
          </el-row>
        </div>
      </div>
    </el-main>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { ArrowLeft, ArrowDown, Star } from '@element-plus/icons-vue'
import { useUserStore } from '@/stores/user'
import { submissionAPI } from '@/utils/api'

const router = useRouter()
const userStore = useUserStore()

const submissions = ref<any[]>([])
const loading = ref(false)

const formatDate = (date: string) => {
  return new Date(date).toLocaleDateString('zh-CN')
}

const fetchExcellentSubmissions = async () => {
  loading.value = true
  try {
    const data = await submissionAPI.getExcellent()
    submissions.value = data.list || []
  } catch (error) {
    ElMessage.error('获取优秀作业失败')
  } finally {
    loading.value = false
  }
}

const handleLogout = () => {
  userStore.logout()
  router.push('/login')
}

onMounted(() => {
  fetchExcellentSubmissions()
})
</script>

<style scoped lang="scss">
.excellent-submissions {
  width: 100%;
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}

.app-header {
  background-color: #10b981;
  color: white;
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0 20px;
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.1);

  .header-left {
    :deep(.el-button) {
      color: white;

      &:hover {
        background-color: rgba(255, 255, 255, 0.2);
      }
    }
  }

  .header-right {
    .el-dropdown-link {
      cursor: pointer;
      color: white;
      display: flex;
      align-items: center;
      gap: 8px;

      &:hover {
        opacity: 0.8;
      }
    }
  }
}

.main-content {
  flex: 1;
  padding: 20px;
  background-color: #f5f7fa;
}

.container {
  max-width: 1200px;
  margin: 0 auto;
}

.page-header {
  margin-bottom: 30px;

  h2 {
    margin: 0 0 10px 0;
    font-size: 24px;
    color: #1f2937;
  }

  p {
    margin: 0;
    color: #6b7280;
  }
}

.loading {
  padding: 20px;
}

.submissions-list {
  .submission-card {
    cursor: pointer;
    transition: all 0.3s ease;
    height: 100%;

    &:hover {
      box-shadow: 0 8px 24px rgba(0, 0, 0, 0.15);
      transform: translateY(-4px);
    }

    .card-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      gap: 10px;

      .title {
        font-weight: 600;
        color: #1f2937;
        flex: 1;
      }
    }

    .card-content {

      .student-info,
      .info-row {
        display: flex;
        justify-content: space-between;
        margin-bottom: 12px;
        font-size: 14px;

        .label {
          color: #9ca3af;
        }

        .value {
          color: #1f2937;
          font-weight: 500;
        }

        .score {
          color: #10b981;
          font-weight: 600;
          font-size: 16px;
        }
      }

      .comment {
        margin-top: 15px;
        padding-top: 15px;
        border-top: 1px solid #e5e7eb;

        .comment-title {
          margin: 0 0 8px 0;
          font-size: 12px;
          color: #9ca3af;
          font-weight: 600;
        }

        .comment-text {
          margin: 0;
          color: #6b7280;
          font-size: 13px;
          line-height: 1.5;
        }
      }
    }
  }
}

@media (max-width: 768px) {
  .main-content {
    padding: 15px;
  }
}
</style>

// frontend-03/client/src/pages/ExcellentSubmissions.tsx
import { useEffect, useState } from 'react';
import { useLocation } from 'wouter';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { submissionAPI } from '@/lib/api';
import { toast } from 'sonner';
import { ArrowLeft, Award } from 'lucide-react';

export default function ExcellentSubmissions() {
  const [, setLocation] = useLocation();
  const [submissions, setSubmissions] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    fetchExcellentSubmissions();
  }, []);

  const fetchExcellentSubmissions = async () => {
    setLoading(true);
    try {
      const response: any = await submissionAPI.getExcellent();
      if (response?.code === 0) {
        setSubmissions(response.data.list || []);
      } else {
        toast.error('获取优秀作业失败');
      }
    } catch (error) {
      toast.error('获取优秀作业失败');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50">
      {/* 顶部导航 */}
      <nav className="bg-white border-b border-gray-200 shadow-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <Button
            variant="ghost"
            className="gap-2 text-emerald-600 hover:text-emerald-700"
            onClick={() => setLocation('/')}
          >
            <ArrowLeft className="w-4 h-4" />
            返回
          </Button>
        </div>
      </nav>

      {/* 主内容 */}
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="mb-8">
          <div className="flex items-center gap-3 mb-2">
            <Award className="w-8 h-8 text-emerald-600" />
            <h1 className="text-3xl font-bold text-gray-900">优秀作业展示</h1>
          </div>
          <p className="text-gray-500">
            展示所有被标记为优秀的作业提交
          </p>
        </div>

        {loading ? (
          <div className="text-center py-12">
            <div className="inline-block">
              <div className="w-8 h-8 border-4 border-emerald-200 border-t-emerald-600 rounded-full animate-spin"></div>
            </div>
            <p className="text-gray-500 mt-4">加载中...</p>
          </div>
        ) : submissions.length === 0 ? (
          <Card className="text-center py-12">
            <Award className="w-12 h-12 text-gray-300 mx-auto mb-4" />
            <p className="text-gray-500">暂无优秀作业</p>
          </Card>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {submissions.map((submission) => (
              <Card
                key={submission.id}
                className="hover:shadow-lg transition-shadow overflow-hidden"
              >
                <div className="p-6">
                  <div className="flex items-start justify-between mb-4">
                    <div>
                      <h3 className="text-lg font-semibold text-gray-900">
                        {submission.homework?.title}
                      </h3>
                      <p className="text-sm text-gray-500 mt-1">
                        学生: {submission.student?.nickname}
                      </p>
                    </div>
                    <div className="flex items-center gap-1 px-3 py-1 bg-yellow-100 rounded-full">
                      <Award className="w-4 h-4 text-yellow-600" />
                      <span className="text-sm font-semibold text-yellow-600">优秀</span>
                    </div>
                  </div>

                  <div className="space-y-3 mb-4">
                    <div className="flex justify-between text-sm">
                      <span className="text-gray-600">部门</span>
                      <span className="font-medium text-gray-900">
                        {submission.homework?.department_label}
                      </span>
                    </div>
                    <div className="flex justify-between text-sm">
                      <span className="text-gray-600">成绩</span>
                      <span className="font-bold text-emerald-600 text-lg">
                        {submission.score}分
                      </span>
                    </div>
                    <div className="flex justify-between text-sm">
                      <span className="text-gray-600">提交时间</span>
                      <span className="font-medium text-gray-900">
                        {new Date(submission.submitted_at).toLocaleDateString('zh-CN')}
                      </span>
                    </div>
                  </div>

                  {submission.comment && (
                    <div className="p-3 bg-gray-50 rounded-lg border border-gray-200 mb-4">
                      <p className="text-xs text-gray-500 mb-1">评语</p>
                      <p className="text-sm text-gray-700">{submission.comment}</p>
                    </div>
                  )}

                  <Button
                    variant="outline"
                    className="w-full border-emerald-600 text-emerald-600 hover:bg-emerald-50"
                  >
                    查看详情
                  </Button>
                </div>
              </Card>
            ))}
          </div>
        )}
      </main>
    </div>
  );
}
